config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  devise_for :users

   resources :users do
     resources :comments
    #  resources :songs
   end

 resources :welcome
 resources :songs

 # root "song#index"
 get '/about' => "welcome#about"


# root "comments#index"
# resources :comments

# root 'artists#index'
resources :artists
get '*path' => redirect('/')
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
   user ||= User.new # guest user (not logged in)
   can :read, Comment

   can [:create, :update, :destroy], Comment do |comment|
     comment.user == user
   end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :song
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artists
  has_many   :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  include CanCan::ControllerAdditions
  rescue_from CanCan::AccessDenied do |exception|
    flash[:notice] = "Access denied!"
    flash.keep(:notice)
    redirect_to root_url
end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  # index
  def index
    @artists = Artist.all
  end

  # new
  def new
    @artist = Artist.new
  end

  # create
  def create
    @artist = Artist.create!(artist_params)
    # render text: params

    redirect_to "/artists/#{@artist.id}"
  end

  #show
  def show
    @artist = Artist.find(params[:id])
  end

  # edit
  def edit
    @artist = Artist.find(params[:id])
  end


  # update
  def update
    @artist = Artist.find(params[:id])
    @artist.update(artist_params)

    redirect_to "/artists/#{@artist.id}"
  end

  # destroy
  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy

    redirect_to "/artists"
  end

  private
  def artist_params
    params.require(:artist).permit(:name, :photo_url, :nationality)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource only: [:edit, :update, :destroy]
  # before_filter :authenticate_user!, except: [:index]

# GET /comments
  def index
    @user = current_user
    @comments = Comment.all
  end

  # GET /comments/new
  def new
    @user = current_user
    @comment = @user.comments.new
end

# Comment /comments
  def create
  @user = current_user
    @comment = @user.comments.create(comment_params)

    redirect_to user_comment_path(@user, @comment)
end

# GET /comments/1
  def show
    @user = current_user
    @comment = @user.comments.find(params[:id])

  end


  def edit
    @user = current_user
    @comment = @user.comments.find(params[:id])
  end

# PATCH/PUT /posts/1
  def update
    @user = current_user
    @comment = @user.comments.find(params[:id])

    if @comment.update(comment_params)
      redirect_to user_comment_path(@user)
    else
      render 'edit'
    end
  end

# DELETE /comments/1
  def destroy
    @user = current_user
    @comment = @user.comments.find(params[:id])
    @comment.destroy
    redirect_to user_comments_path(@user)
  end

  private
  # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:body, :author, :user_id)
    end
  end

app/controllers/song_controller.rb
class SongController < ApplicationController

  def index
    @songs = Song.all
  end

  # new
  def new
    @artist = Artist.find(params[:artist_id])
    @song = Song.new
  end

  # create
  def create
    @artist = Atrist.find(params[:artist_id])
    @song = Song.create!(song_params.merge(artist: @artist))
    redirect_to artist_song_path(@artist, @song)
  end

  #show
  def show
    @song = Song.find(params[:id])
  end

  # edit
  def edit
    @song = Song.find(params[:id])
  end

  # update
  def update
    @song = Song.find(params[:id])
    @artist = Artist.find(params[:artist_id])
    @song.update(song_params.merge(artist: @artist))
    redirect_to artist_song_path(@song.artist, @song)
  end

  # destroy
  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    redirect_to songs_path
  end

  private
  def song_params
    params.require(:song).permit(:title, :album, :preview_url, :artist_id)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
    @songs = Song.all
  end

  # new
  def new
    # @artist = Artist.find(params[:artist_id])
    @song = Song.new
  end

  # create
  def create
    # @artist = Artist.find(params[:artist_id])

    @song = Song.create(song_params)
    redirect_to songs_path
    # redirect_to artist_song_path(@artist, @song)
  end

  #show
  def show
    @song = Song.find(params[:id])
    @artist = Artist.find(@song.artist_id)
  end

  # edit
  def edit
    @song = Song.find(params[:id])
    # @song.edit(params[:id])
    # redirect_to songs_path
  end

  # update
  def update
    @song = Song.find(params[:id])
    # @artist = Artist.find(params[:artist_id])
    @song.update(song_params)
    redirect_to song_path
  end

  # destroy
  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    redirect_to songs_path
  end

  private
  def song_params
    params.require(:song).permit(:title, :album, :preview_url, :artist_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def about

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/song_helper.rb
module SongHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/artists/_disqus.html.erb
<div id="disqus_thread">
<script >
//  var disqus_shortname  = 'Artists';
//  var disqus_identifier = '<%= @artist.id %>';
//  var disqus_title      = '<%= @artist.name %>';
//  var disqus_url        = '<%= url_for([@artist, {only_path: false}]) %>';
    /**
     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

//     var disqus_config = function () {
//     this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
//     this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
//     };

    (function() { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = '//portfolio-blog-5.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
</div>

app/views/artists/_form.html.erb
<%= form_for @artist do |f| %>
<div class="container">
    <div class="form-group">
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
    </div>
    <div class="form-group">
  <%= f.label :photo_url %><br>
  <%= f.text_field :photo_url%><br>
    </div>
    <div class="form-group">
  <%= f.label :nationality %><br>
  <%= f.text_field :nationality %><br>
  </div>
  <div class="form-group">
  <%= f.submit "Create Artist", class: "btn btn-primary" %>

<% end %>

app/views/artists/edit.html.erb
<h2>Edit Artist</h2>

<%= render "form" %><br>

<br><%= link_to 'Back', artists_path(current_user), class: 'btn btn-primary btn-xs' %>

app/views/artists/index.html.erb
  <div class="row">
     <div class="col-lg-12">
      <h2>Artists</h2><br>
    </div>
  </div>
 <%= link_to 'NEW ARTIST (+) ', new_artist_path %><br>
<br>
<ul>
  <% @artists.each do |artist| %>
    <li>
      <a href="/artists/<%= artist.id %>">
        <%= artist.name %>
      </a>
    </li>

  <% end %>
</ul>

app/views/artists/new.html.erb
<h2> ADD NEW ARTIST </h2>

<%= render 'form' %><br>

<br><%= link_to 'Back', artists_path(current_user), class: 'btn btn-primary btn-xs' %>

app/views/artists/show.html.erb
<h1>Voila!</h1>
<h2><%= @artist.name %></h2>
<h4><%= @artist.nationality %></h4>
<!-- <div height="300px" width="300px"><%= image_tag @artist.photo_url %></div> -->
<img src='<%= @artist.photo_url %>' height="400px" width="400px">
<h3>Songs<%= link_to'(+)', new_song_path(@song)%></h3>

<ul>
  <% @artist.songs.each do |song| %>
    <li>
      <%= link_to song.title, song_path(song) %>
    </li>
  <% end %>
</ul>

<br><%= link_to 'Edit', edit_artist_path(@artist), class: 'btn btn-primary btn-xs' %><br>
<br><%= link_to 'Delete', (@artist), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %><br>
<br><%= link_to 'Back', artists_path, class: 'btn btn-primary btn-xs' %>
<%= render "disqus" %>

app/views/comments/_form.html.erb
<%= form_for([@user,@comment]) do |f| %>
<div class="container">
    <div class="form-group">
  <%= f.label :author %><br>
  <%= f.text_field :author %><br>
    </div>
    <div class="form-group">
  <%= f.label :body %><br>
  <%= f.text_area :body, placeholder: "Write your comment", class: "form-control" %><br>
    </div>

    <div class="form-group">
      <%= f.submit "Submit comment", class: "btn btn-primary" %>
    </div>
</div>
<% end %>

app/views/comments/comment.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h3 class="comment-info"> Here are your comments...
      </h3>
    </div>
  </div>
<div class="row">
    <div class="col-xs-12">
      <h3><%= link_to "comments", user_comment_path, class: "btn btn-md btn-primary" %></h3>
      <a href="/user_comments_path">Comments</a>
      
    </div>
</div>
</div>

app/views/comments/edit.html.erb
<h2>Edit comments</h2>

<%= render 'form' %>

<%= link_to 'Back', user_comments_path(current_user), class: 'btn btn-primary btn-xs' %>

app/views/comments/index.html.erb
<div class="row">
   <div class="col-lg-12">
     <h2>Reviews</h2><br>
   </div>
</div>
   <%= link_to  'NEW Comment (+) ', new_user_comment_path(@user) %><br>
<br>
<ul>
<% @comments.each do |comment| %>
<li>
<a href="/comments/<%= comment.id %>">
  <%= "#{comment.author} - #{comment.body}" %>
</a>
<li>
<% end %>
</ul>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', user_comments_path(current_user), class: 'btn btn-primary btn-xs' %>

app/views/comments/show.html.erb
<h1>View Comment</h1>
<h2>
<%= @comment.author %>:

<br>
<br>

<%= @comment.body %>
<br>
</h2>
<br><%= link_to 'Edit', edit_user_comment_path(@user), class: 'btn btn-primary btn-xs' %><br>

<br><%= link_to 'Delete', user_comment_path(@user), :method => 'delete', data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs'  %><br>


<br><%= link_to 'Back', user_comments_path, class: 'btn btn-primary btn-xs' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dj_Playit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<%= render 'shared/nav' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default">
 <div class="container">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#myNavbar" aria-expanded="false">
       <span class="sr-only">Toggle navigation</span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
     </button>
   <a class="navbar-brand" href="#">Dj-Playit</a>
  </div>
  <div class="collapse navbar-collapse" id="myNavbar">
   <ul class="nav navbar-nav">
      <li><%= link_to 'About', about_path %></li>
      <li><%= link_to 'Artists', artists_path %></li>
      <li><%= link_to 'Songs', songs_path %></li>
      <!-- <li><%= link_to 'Reviews', user_comments_path(:user_id) %></li> -->
   </ul>
   <ul class="nav navbar-nav navbar-right">
     <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <li><%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <li><%= link_to "Sign up", new_user_registration_path %>
      <li><%= link_to "Login", new_user_session_path  %>
      <% end %>
   </ul>
  </div>
 </div>

</nav>

app/views/song/index.html.erb
<%= render 'shared/nav' %>
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h2 class="grey">No Hassle. Just pick a song.</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-4 col-lg-offset-4">
      <%= link_to "Get a song.", song_path, class: 'center', id: 'get-song' %>
    </div>
  </div>
</div>

app/views/songs/_disqus.html.erb
<div id="disqus_thread">
<script>
//  var disqus_shortname  = 'Songs';
//  var disqus_identifier = '<%= @song.id %>';
//  var disqus_title      = '<%= @song.title %>';
//  var disqus_url        = '<%= url_for([@song, {only_path: false}]) %>';
    /**
     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

//     var disqus_config = function () {
//     this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
//     this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
//     };

    (function() { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = '//portfolio-blog-5.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
</div>

app/views/songs/_form.html.erb
<%= form_for @song do |f| %>
    <div class="container">
    <div class="form-group">
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
    </div>
    <div class="form-group">
  <%= f.label :album %><br>
  <%= f.text_area :album %><br>
    </div>
    <div class="form-group">
  <%= f.label :preview_url %><br>
  <%= f.text_area :preview_url %><br>
    </div>
    <div class="form-group">
 <%= f.label :artist_id %><br>
 <%= f.text_area :artist_id %><br>
    </div>
    <div class="form-group">
      <%= f.submit  class: "btn btn-primary" %>
    </div>
</div>
<% end %>

app/views/songs/edit.html.erb
<h2>Edit Song</h2>

<%= render "form" %>

<%= link_to 'Back', songs_path(current_user), class: 'btn btn-primary btn-xs' %>

app/views/songs/index.html.erb
<div class="row">
     <div class="col-lg-12">
        <h2>Songs </h2><br>
     </div>
   </div>
   <%= link_to 'NEW SONG (+)', new_song_path %><br>
<br>
<ul>
  <% @songs.each do |song| %>
    <li>
      <a href="/songs/<%= song.id %>">
        <%= "#{song.title} - #{song.album}" %>
      </a>
    </li>
  <% end %>
</ul>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path(current_user), class: 'btn btn-primary btn-xs' %>

app/views/songs/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1 class="listening-info"> You are listening to...</h1>
      <h2><%= link_to @song.title, @song.preview_url, target: '_blank' %></h2>
      <h3>By: <%= @artist.name %></h3>
      <p>Album: <%= @song.album %></p></br>
    </div>
  </div>
</div>

<br><%= link_to 'Edit', edit_song_path(@song), class: 'btn btn-primary btn-xs' %><br>
<br><%= link_to 'Delete', (@song), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %><br>
<br><%= link_to 'Back', songs_path, class: 'btn btn-primary btn-xs' %>
<%= render "disqus" %>

app/views/songs/song.html.erb
 <#%= render 'shared/nav' %> 
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h3 class="listening-info"> You are listening to...
      </h3>
    </div>
  </div>
<div class="row">
    <div class="col-xs-12">
      <h3><%= link_to "Pick a song", song_path, class: "btn btn-md btn-primary", id: "play-again-link" %></h3>
      <a href="/songs">Songs</a>
      <a href="/artists">Artists</a>
    </div>
</div>
</div>

app/views/welcome/about.html.erb
<div class="row">
  <div class="col-lg-6 col-lg-offset-3 well">
    <h3 class="text-center">ABOUT</h3>
    <hr>
    <h3>What?</h3>
    <p>
      Dj-Playit is a music app built using Ruby on Rails. It's free &amp; completely open source. You can check the source on <a href="https://github.com/ramata/Dj-Playit"><%= fa_icon 'github' %> Github</a>. Also take a look at the demo deployed to <a href="https://salty-falls-67437.herokuapp.com">Heroku</a>.
    </p>
    <br>
    <h3>Why?</h3>
    <p>
      I am not building the next Spotify. Given that there are enough music apps already I don't want to end up launching one. Pointless! So why am I building it? I want to try and learn how to develop a social network using my music app and in the process show you how easy it is done using Rails.</p>
    <br>
    <h3>How?</h3>
    <p>
      As stated above it's a Ruby on Rails application. Frontend is developed using Twitter Bootstrap. Database is SQLite for development and Postgresql for production.
    </p>
    <br>
    <a href="https://github.com/ramata/Dj-Playit" class="btn btn-warning">
      <%= fa_icon 'star' %> Star it
    </a>
    <a href="https://github.com/ramata/Dj-Playit" class="btn btn-primary">
      <%= fa_icon 'code-fork' %> Fork it
    </a>
  </div>
</div>

app/views/welcome/index.html.erb
<%= audio_tag "audio.m4a", class: "audio-play" %>

<h1 class="btn btn-primary audioButton">Dj-Playit!</h1>